name: workspace

description: "A Flutter workspace for ai_edge and its examples."

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

workspace:
  - packages/ai_edge
  - packages/ai_edge_fc
  - examples/ai_chat
