name: workspace

description: "A Flutter workspace for ai_edge and its examples."

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

workspace:
  - packages/ai_edge
  - packages/ai_edge_fc
  - packages/ai_edge_model_dl

dev_dependencies:
  lcov_excluder: ^0.2.0
